export const data = [
  {
    nombre: "The Legend of Zelda: Breath of the Wild",
    fecha_lanzamiento: "2017-03-03",
    precio: 59.99,
    protagonistas: ["Link"],
    genero: "Aventura, Mundo abierto",
  },
  {
    nombre: "Super Mario Odyssey",
    fecha_lanzamiento: "2017-10-27",
    precio: 59.99,
    protagonistas: ["Mario", "Cappy"],
    genero: "Plataformas, Aventura",
  },
  {
    nombre: "Red Dead Redemption 2",
    fecha_lanzamiento: "2018-10-26",
    precio: 59.99,
    protagonistas: ["Arthur Morgan", "John Marston"],
    genero: "Acción, Aventura, Mundo abierto",
  },
  {
    nombre: "The Witcher 3: Wild Hunt",
    fecha_lanzamiento: "2015-05-19",
    precio: 39.99,
    protagonistas: ["Geralt de Rivia"],
    genero: "Rol, Aventura",
  },
  {
    nombre: "Minecraft",
    fecha_lanzamiento: "2011-11-18",
    precio: 26.95,
    protagonistas: ["Steve", "Alex"],
    genero: "Construcción, Supervivencia",
  },
  {
    nombre: "Uncharted 4: A Thief's End",
    fecha_lanzamiento: "2016-05-10",
    precio: 39.99,
    protagonistas: ["Nathan Drake", "Elena Fisher"],
    genero: "Acción, Aventura",
  },
  {
    nombre: "Halo: Infinite",
    fecha_lanzamiento: "2021-12-08",
    precio: 59.99,
    protagonistas: ["Master Chief", "Cortana"],
    genero: "Shooter en primera persona, Ciencia ficción",
  },
  {
    nombre: "God of War (2018)",
    fecha_lanzamiento: "2018-04-20",
    precio: 49.99,
    protagonistas: ["Kratos", "Atreus"],
    genero: "Acción, Aventura",
  },
  {
    nombre: "Final Fantasy XV",
    fecha_lanzamiento: "2016-11-29",
    precio: 39.99,
    protagonistas: [
      "Noctis Lucis Caelum",
      "Ignis Scientia",
      "Gladiolus Amicitia",
      "Prompto Argentum",
    ],
    genero: "Rol, Acción",
  },
  {
    nombre: "Overwatch",
    fecha_lanzamiento: "2016-05-24",
    precio: 39.99,
    protagonistas: ["Tracer", "Winston", "Reaper", "Mercy", "Genji"],
    genero: "Shooter en primera persona, Multijugador",
  },
  {
    nombre: "The Elder Scrolls V: Skyrim",
    fecha_lanzamiento: "2011-11-11",
    precio: 39.99,
    protagonistas: ["Dragonborn"],
    genero: "Rol, Aventura",
  },
  {
    nombre: "The Last of Us Part II",
    fecha_lanzamiento: "2020-06-19",
    precio: 59.99,
    protagonistas: ["Ellie", "Abby"],
    genero: "Acción, Aventura",
  },
  {
    nombre: "Animal Crossing: New Horizons",
    fecha_lanzamiento: "2020-03-20",
    precio: 59.99,
    protagonistas: ["El jugador"],
    genero: "Simulación, Social",
  },
  {
    nombre: "Cyberpunk 2077",
    fecha_lanzamiento: "2020-12-10",
    precio: 59.99,
    protagonistas: ["V"],
    genero: "Acción, Rol, Ciencia ficción",
  },
  {
    nombre: "Ghost of Tsushima",
    fecha_lanzamiento: "2020-07-17",
    precio: 59.99,
    protagonistas: ["Jin Sakai"],
    genero: "Acción, Aventura",
  },
  {
    nombre: "Assassin's Creed Odyssey",
    fecha_lanzamiento: "2018-10-05",
    precio: 59.99,
    protagonistas: ["Kassandra", "Alexios"],
    genero: "Acción, Aventura, Rol",
  },
  {
    nombre: "Call of Duty: Warzone",
    fecha_lanzamiento: "2020-03-10",
    precio: 0.0, // Free-to-play
    protagonistas: ["Jugadores"],
    genero: "Shooter en primera persona, Battle Royale",
  },
  {
    nombre: "The Legend of Zelda: Ocarina of Time",
    fecha_lanzamiento: "1998-11-21",
    precio: 39.99,
    protagonistas: ["Link", "Zelda"],
    genero: "Aventura, Rol",
  },
  {
    nombre: "Splatoon 2",
    fecha_lanzamiento: "2017-07-21",
    precio: 59.99,
    protagonistas: ["Inkling", "Octoling"],
    genero: "Shooter en tercera persona, Multijugador",
  },
  {
    nombre: "Tetris",
    fecha_lanzamiento: "1984-06-06",
    precio: 9.99,
    protagonistas: ["Jugadores"],
    genero: "Puzzle",
  },
];
